# Generated by Django 3.1.3 on 2020-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201203_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=50),
        ),
    ]
