# Generated by Django 3.1.3 on 2020-12-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201203_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.TextField(default='#'),
        ),
    ]
