# Generated by Django 3.1.3 on 2020-12-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201209_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.TextField(default='#'),
        ),
    ]
