# Generated by Django 3.1.3 on 2020-12-10 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='about',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='abouttxt',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='link',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='picname2',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='picurl',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='picurl2',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='set_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='tell',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='tw',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='yt',
        ),
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manager',
            name='utxt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
